= MEHLISSA: A Medical Holistic Simulation Architecture for Nanonetworks in Humans
Regine Wendt <regine.wendt@uni-luebeck.de>
v1.1, 2024-06-02

Lisa Y. Debus <debus@ccs-labs.org>
v2.0, 2024-10-25

== Introduction

MEHLISSA is a program that simulates the global movement of objects in the human body. Its main purpose is to model the work environment of medical nanodevices. 
MEHLISSA is an extension and replacement of the BloodVoyagerS Module for ns-3 (https://github.com/RegineWendt/blood-voyager-s). 
MEHLISSA 2.0 removed the ns3 dependecies and is a stand-alone program.

Please checkout the literature folder for more information of the model and scenario. If you use MEHLISSA cite at least:

Regine Wendt und Stefan Fischer: „MEHLISSA: a medical holistic simulation architecture for nanonetworks in humans“ Proceedings of the 7th ACM International Conference on Nanoscale Computing and Communication · Virtual Event USA: ACM, Sep. 2020, S. 1–6 · isbn: 978-1-4503-8083-6 · doi: 10.1145/ 3411295.3411305 · url: https://dl.acm.org/doi/10.1145/3411295.3411305

You find detailed descriptions on the complete model, uml structures, scenarios, calculations etc. in Regine's dissertation (in German). 

If you use information from Regine's disseration, i.e. the scenarios, cite in addition: 

Regine Wendt: „Einsatz von Nanotechnologien in der Präzisionsmedizin“ · Dissertation · Universität zu Lübeck, 2024

If you use fingerprinting cite Regine's dissertation and: 

Regine Wendt, Florian-Lennert Lau, Lena Unger und Stefan Fischer: „Proteome Fingerprinting as a Localization Scheme for Nanobots“ · Proceedings of the 10th ACM International Conference on Nanoscale Computing and Communication · NANOCOM ’23 · Coventry, United Kingdom: Association for Computing Machinery, 2023, S. 27–32 · isbn: 9798400700347 · doi: 10.1145/3576781.3608728 · url: https://doi.org/10.1145/3576781.3608728


== Features

  - 3D coordinates of major vessels and organs
  - Simulates permanent movement of nanodevices in cardiovascular system
  - Injection of nanodevices in specific vessels
  - Detection of nanodevices in specific vessel
  - Provides global position data of nano devices
  - Simulates Nanolocators, Nanocollectors, Nanoparticles, Cancer Cells, CAR-T Cells, and T Cells
  - Provides interaction functionality for the simulated particles, e.g., mitosis based on static growth rate, mitosis triggered by particle interaction, cell fratricide, localization, detection

== Important Parameters

  - Number of nanobots `m_numberOfNanobots`
  - Injection vessel `m_injectionVessel [1-95]`
  - Detection vessel `m_detectionVessel [1-95]`
  - Simulation duration in seconds `m_simulationDuration`
  - Duration between each simulation step `m_deltaT`
  - Velocities: `m_arteryVelocity = 10 cm/s, m_veinVelocity = 3,7 cm/s, m_organVelocity = 1cm/s`

== Tutorial/Get started

== Compile MEHLISSA Version 2.0

To compile MEHLISSA 2.0 you will need to have CMake installed on your computer.
For the compilation first create the CMake files and then compile the project.
To do this, navigate into the mehlissa/src folder and execute the following commands:

```
   
   CMake .

   make . clean all
```

== Run MEHLISSA Version ns-3.36
    SIMDURATION=   # simulation duration in seconds
    SIMSTEP= # simulation step duration
    NUMOFNANOBOTS= # number of nanobots
    INJECTVESSEL=  # injection vessel [1-95]
    DETECTVESSEL=  # detection vessel [1-95]
    INJECTIONTIME= # time of CAR-T cell injection
    NUMOFCOLLECTORS= # specialised nanodevices that collect messages
    NUMOFLOCATORS= # specialised nanodevices that can locate nine organs
    NUMCANCERCELLS= # basic Leukemia cancerous cells
    NUMCARTCELLS= # basic CAR-T cells
    NUMTCELLS= # basic T cells
    PARTICLEMODE = # Mode 1 simulates LDL particles, Mode 2 simulates Liquid Biopsy
    GWFILE= # file to save the gateway detection output
    SIMFILE= # file to save the simulation output


    for the simulation as in MEHLISSA run  MEHLISSA2.0 by calling
    ./bin/MehlissaCancer --simulationDuration=$SIMDURATION --simulationStep=$SIMSTEP --numCancerCells=$NUMCANCERCELLS --numCarTCells=$NUMCARTCELLS --numTCells=$NUMTCELLS --injectionTime=$INJECTTIME --injectionVessel=$INJECTVESSEL --detectionVessel=$DETECTVESSEL --simFile=$SIMFILE  --gwFile=$GWFILE

    ./bin/start-mehlissa --simulationDuration=$SIMDURATION, --numOfNanobots=$NUMOFNANOBOTS, --injectionVessel=$INJECTVESSEL"
    
    or with default values
    ./bin/MehlissaCancer

    to simulate nanocollectors and nanolocators
    ./bin/MehlissaCancer --simulationDuration=$SIMDURATION --numOfNanobots=$NUMOFNANOBOTS --injectionVessel=$INJECTVESSEL --numOfCollectors=$NUMOFCOLLECTORS --numOfLocators=$NUMOFLOCATORS"

    In addition you can use other bodymodels by changing the used data/vasculature.csv and data/transitions95.csv files in Bloodcircuit.h.

    
The simulation returns a csv-file (default value: output/csvNano.csv) with the position data of the simulated nanobots or other devices and particles and their status in every timestep and a csv-file (default value: output/gwNano.csv) with the number of detected CAR-T cells at the gateway in every timestep. 

